baseurl = "https://pointerpodcast.it"
languageCode = "en-us"
theme = "hugo-theme-stack-podcast"
paginate = 5.0
title = "Pointer Podcast"
DefaultContentLaxnguage = "en"
assetDir = "static"


[permalinks]
post = "/p/:slug/"
page = "/:slug/"
guests = "/guests/:slug"

[params]
mainSections = [
  "post",
  "episode"
]
featuredImageField = "image"
rssFullContent = true
url = "https://pointerpodcast.it"

Summary = "Puntatori alla tecnologia"



  [params.podcast]
    url = "https://pointerpodcast.it/"
    podcastTitle = "Pointer Podcast"
    podcastDescription = "PointerPodcast è realizzato da Alessandro, Eugenio e Luca, tre studenti di informatica. Quotidianamente, tra una lezione e un progetto o tra una birra e pizza ci siamo trovati a parlare di tecnologia, da qui è nata l'idea di allargare il nostro pubblico"
    rssLink = "/index.xml"
    PodcastSubtitle = "Puntatori alla tecnologia"
    podcastSummary = "PointerPodcast è realizzato da Alessandro, Eugenio e Luca, tre studenti di informatica. Quotidianamente, tra una lezione e un progetto o tra una birra e pizza ci siamo trovati a parlare di tecnologia, da qui è nata l'idea di allargare il nostro pubblico"
    podcastAuthor = "PointerPodcast"
    podcastEmail = "info@pointerpodcast.it"
    podcast_image = "https://pointerpodcast.it/wp-content/uploads/2020/12/Logo_Podcast.png"
    itunesCategory1 = "Technology"
    itunesCategory2 = "Interviews"
    itunesCategory3 = "News"
    

  [params.footer]
  since = 2019.0

  [params.dateFormat]
  published = "Jan 02, 2006"
  lastUpdated = "Jan 02, 2006 15:04 MST"

  [params.sidebar]
  subtitle = "Puntatori alla tecnologia"

    [params.sidebar.avatar]
    local = true
    src = "img/logo_puntata.png"

  [params.article]
  math = false

    [params.article.license]
    enabled = true
    default = "Licensed under CC BY-NC-SA 4.0"

  [params.comments]
  enabled = true
  provider = "disqus"

    [params.comments.utterances]
    issueTerm = "pathname"

    [params.comments.remark42]

  [params.widgets]
  enabled = [
    "search",
    "archives",
    "tag-cloud",
  ]


    [params.widgets.archives]
    limit = 5.0

    [params.widgets.tagCloud]
    limit = 10.0

  [params.opengraph]

    [params.opengraph.twitter]
    card = "summary_large_image"

  [params.defaultImage]

    [params.defaultImage.opengraph]
    enabled = false
    local = false

  [params.colorScheme]
  toggle = true
  default = "auto"

  [params.imageProcessing]

    [params.imageProcessing.cover]
    enabled = true

    [params.imageProcessing.content]
    enabled = true

[menu]

  [[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = -100.0
  pre = "home"

[related]
includeNewer = true
threshold = 60.0
toLower = false

  [[related.indices]]
  name = "tags"
  weight = 100.0

  [[related.indices]]
  name = "categories"
  weight = 200.0

[markup]

  [markup.highlight]
  noClasses = false

  [markup.goldmark.renderer]
  unsafe = true

  